# Generated by Django 5.0.11.dev20250107212806 on 2025-01-12 21:00

import django_mongodb_backend.fields
import polls.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_alter_question_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=polls.models.Question
                    ),
                ),
            ],
        ),
    ]
